// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      // Corrected line
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuMPGmvkrG7asuDFZv4h7mcYgSJ7r1ttQ',
    appId: '1:1081958068030:android:50f8d45acb06fb5d19066f',
    messagingSenderId: '1081958068030',
    projectId: 'al-wasit-f0c5c',
    storageBucket: 'al-wasit-f0c5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuMPGmvkrG7asuDFZv4h7mcYgSJ7r1ttQ',
    appId: '1:1081958068030:ios:0b68e6e0a854f52c19066f',
    messagingSenderId: '1081958068030',
    projectId: 'al-wasit-f0c5c',
    storageBucket: 'al-wasit-f0c5c.appspot.com',
    iosBundleId: 'com.example.shopAppAHN',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuMPGmvkrG7asuDFZv4h7mcYgSJ7r1ttQ',
    appId: '1:1081958068030:web:98fd05e5b9759dec19066f',
    messagingSenderId: '1081958068030',
    projectId: 'al-wasit-f0c5c',
    authDomain: 'al-wasit-f0c5c.firebaseapp.com',
    storageBucket: 'al-wasit-f0c5c.appspot.com',
    measurementId: 'G-PBRCEQM64L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuMPGmvkrG7asuDFZv4h7mcYgSJ7r1ttQ',
    appId: '1:1081958068030:ios:0b68e6e0a854f52c19066f',
    messagingSenderId: '1081958068030',
    projectId: 'al-wasit-f0c5c',
    storageBucket: 'al-wasit-f0c5c.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuMPGmvkrG7asuDFZv4h7mcYgSJ7r1ttQ',
    appId: '1:1081958068030:web:9172d61f4761e07d19066f',
    messagingSenderId: '1081958068030',
    projectId: 'al-wasit-f0c5c',
    authDomain: 'al-wasit-f0c5c.firebaseapp.com',
    storageBucket: 'al-wasit-f0c5c.appspot.com',
    measurementId: 'G-EW1C7CVDY9',
  );
}
